### ISSUE TITLE
Aguardando Código

### ISSUE THREAD

**Issue by Marii-brito** [PetJournal/petjournal.android#10]
Definição:

Como usuário, quero poder digitar o código de verificação para recuperar minha senha.

Descrição:

Nessa tela o objetivo é que o usuário consiga recuperar a senha caso ele tenha perdido ou esquecido. E para isso ele deverá passar por três processos: enviar o código de recuperação para o email ou telefone, digitar o código recebido e criar uma senha nova. Se esses três passos forem feitos, o usuário poderá ter acesso ao aplicativo novamente.

Protótipo:

![Image](https://user-images.githubusercontent.com/129445779/232582236-fdbef462-ea4d-4784-95c9-ee028d973a99.png)

Critérios de Aceite:

> O código de verificação deve conter 6 dígitos numéricos. 

> Quando` o usuário digitar o código de verificação corretamente o botão “Enviar” deverá ser habilitado, ao clicar no botão o mesmo deve ser redirecionado para tela onde poderá criar a nova senha.

> Caso o usuário selecione a opção “reenviar código", ele será redirecionado para tela onde é possível adicionar o emailpara receber o novo código de verificação.

> Se o sistema, após o clique em “Enviar” verificar que o código de verificação esteja incorreto, uma mensagem de aviso deve ser apresentada na tela: 

`“O código de verificação que você inseriu não é válido. Verifique o código e tente novamente”.`

> Se o sistema, após o clique em “Enviar” verificar que o código de verificação esteja correto, o usuário deverá ser redirecionado para tela “[Troque a Senha](https://docs.google.com/document/d/1aqk79LZt29eRKpKNySt-zJNhHLJzKLJz/edit?usp=sharing&ouid=105032028308354704003&rtpof=true&sd=true)”.

> Associações:

[Troque a Senha](https://docs.google.com/document/d/1aqk79LZt29eRKpKNySt-zJNhHLJzKLJz/edit?usp=sharing&ouid=105032028308354704003&rtpof=true&sd=true)

**Comment by Lsortudo** [comment]
## Tasks

### Definir o layout
Criar os componentes da tela de **aguardando o código**, como:

- [ ] **Header**
	- [ ] **REFATORAÇÂO**
	- [ ] Logo projeto;
	- [ ] Texto código enviar email;
	- [ ] Texto código email enviado;
	

- [ ] **VerificationCode**
	- [ ] **REFATORAÇÂO**
	- [ ] OTP TextField: 
	    - 6 digitos separados;
	    - Foco automatico para passar para o próximo campo;
	    - Estilização para campos preenchidos/vagos;
	- [ ] Texto reenviar código;
	- [ ] Texto código email enviado;


- [ ] **Footer**
	- [ ] **REFATORAÇÂO**
	- [ ] Botão de enviar;
	- [ ] Texto dica sobre email;
	- [ ] Texto código email enviado;



### Definir a lógica
Criar a lógica responsável por fazer comunicação entre as partes do app, como:

 - [ ] **Data**
	 - [ ] Mockar dado básico para fim de testes;

 - [ ] **Domain**

 - [ ] **ViewModel**
	 - [ ] Implementar observables para observar a UI;
	 - [ ] Atualizar a UI baseado em dados providos pela camada de Data;
