### ISSUE TITLE
Cadastro do Usuário

### ISSUE THREAD

**Issue by victorjoaoss** [PetJournal/petjournal.android#3]
https://github.com/PetJournal/petjournal.product/issues/2

**Comment by gusoliveira21** [comment]
## Tasks
- [x] Definir o layout da tela: Use Case
	- Criação de campos:
	- [ ] nome, 
	- [ ] sobrenome, 
	- [ ] e-mail, 
	- [ ] telefone, 
	- [ ] senha
	- [ ] confirmação de senha

- [ ] Implementar a validação dos campos
	Número mínimo ``2`` e máximo de ``60`` caracteres ?
	caracteres permitidos 
	formato correto de e-mail 
	formato correto de telefone
	formato correto da senha ? 
- [ ] Implementar mensagem de erro em caso de um campo for inválido. 
	``exiba uma mensagem de erro abaixo do campo``
- [ ] Habilitar o botão "Continuar" quando tudo estiver preenchido corretamente.

### Clicar no botão "Continuar", envia os dados para o back-end que retorna uma resposta positiva ou negativa:

- Implementar:

	- [ ] Email já cadastrado:
		- Exibe mensagem de erro avisando que email já existe na base de dados. ``É ético? terceiros poderiam consultar indiretamente e-mails cadastrados na base de dados``.
	- [ ] Email Não Cadastrado: 
		- Exibe uma mensagem avisando que um e-mail o foi enviado. Pedir para confirmar o email e ativar a conta.
		- ``Como funcionará a confirmação do email? O que ela vai me retornar? Como?``
		- O encaminha para a tela de login.

- [ ] Implementar o link de política de privacidade. ``Obrigatório para aplicativos que vão ser publicados na loja``.
- [ ] Testar a tela.
